version: '3.8'
services:
  db:
    image: postgres:15
    environment:
      POSTGRES_USER: evuser
      POSTGRES_PASSWORD: evpass
      POSTGRES_DB: evdb
    volumes:
      - db_data:/var/lib/postgresql/data
  redis:
    image: redis:7
    ports:
      - '6379:6379'
  backend:
    build: ./backend
    environment:
      DATABASE_URL: postgresql://evuser:evpass@db:5432/evdb
      REDIS_URL: redis://redis:6379/0
    ports:
      - '8000:8000'
    depends_on:
      - db
      - redis
    volumes:
      - ./backend/app/models:/app/app/models
  nginx:
    image: nginx:stable
    ports:
      - '80:80'
      - '443:443'
    volumes:
      - ./nginx/conf.d:/etc/nginx/conf.d:ro
      - ./nginx/certs:/etc/letsencrypt
    depends_on:
      - backend
  frontend:
    build: ./frontend
    ports:
      - '5173:5173'
volumes:
  db_data: